=== ihaoqi/jsfboot/sources/jsfboot-bundle/sources/jsfboot-configure-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://jsfboot.easyeip.com/jsfboot-configure" 
		elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://jsfboot.easyeip.com/jsfboot-configure">

    <element name="jsfboot-configure" type="tns:JsfbootConfigureType"></element>
    
    <complexType name="JsfbootConfigureType">
    	<sequence>
    		<element name="app-version" type="tns:AppVersionType"
    			minOccurs="1" maxOccurs="1">
    			<annotation>
    				<documentation>软件版本信息</documentation>
    			</annotation>
    		</element>
            <element name="app-options" type="tns:AppOptionsType" minOccurs="1" maxOccurs="1"></element>
    		<element name="service-conf" type="tns:ServiceConfType"
    			minOccurs="0" maxOccurs="unbounded">
    			<annotation>
    				<documentation>服务参数配置</documentation>
    			</annotation>
    		</element>
    	</sequence>
    </complexType>

    <complexType name="AppVersionType">
        <all>
    		<element name="product-name" type="string" minOccurs="1" maxOccurs="1">
    			<annotation>
    				<documentation>产品名称，如某某管理系统</documentation>
    			</annotation>
    		</element>
    		<element name="product-version" type="string" minOccurs="1" maxOccurs="1">
    			<annotation>
    				<documentation>产品版本号，如1.2.3</documentation>
    			</annotation>
    		</element>
            <element name="product-title" type="string" minOccurs="1" maxOccurs="1"></element>
            <element name="product-description" type="string" minOccurs="0" maxOccurs="1">
    			<annotation>
    				<documentation>产品介绍，支持HTML。</documentation>
    			</annotation>
    		</element>
    		<element name="company-name" type="string" minOccurs="0" maxOccurs="1">
    			<annotation>
    				<documentation>公司名称</documentation>
    			</annotation>
    		</element>
    		<element name="company-description" type="string" minOccurs="0" maxOccurs="1">
    			<annotation>
    				<documentation>公司介绍，支持HTML。</documentation>
    			</annotation>
    		</element>
    	</all>
    </complexType>
    
    <complexType name="ServiceConfType">
    	<sequence>
    		<element name="service-param" type="tns:ServiceParamType" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    	<attribute name="name" type="string" use="required"></attribute>
    </complexType>

    <complexType name="ServiceParamType">
    	<attribute name="name" type="string" use="required"></attribute>
    	<attribute name="value" type="string" use="optional">
    		<annotation>
    			<documentation>属性文本值；</documentation>
    		</annotation></attribute>
    	<attribute name="ref-bean" type="string" use="optional">
    		<annotation>
    			<documentation>jsf或spring的bean名称</documentation>
    		</annotation></attribute>
    	<attribute name="ref-service" type="string" use="optional">
    		<annotation>
    			<documentation>jsfstarter服务名称</documentation>
    		</annotation></attribute>
    </complexType>

    <complexType name="AppOptionsType">
    	<sequence>
    		<element name="site-theme" type="string" minOccurs="1"
    			maxOccurs="1">
    			<annotation>
    				<documentation>前台主题名称</documentation>
    			</annotation>
    		</element>
            <element name="admin-theme" type="string" minOccurs="1" maxOccurs="1">
            	<annotation>
            		<documentation>后台主题名称</documentation>
            	</annotation></element>
            <element name="account-realm" type="string" minOccurs="0"
    			maxOccurs="1">
    			<annotation>
    				<documentation>授权适配器，没有就默认为系统自带的；</documentation>
    			</annotation>
            </element>
    	</sequence>
    </complexType>
</schema>

=== ihaoqi/jsfboot/sources/jsfboot-demo/WebContent/WEB-INF/conf/jsfboot-development.xml
<?xml version="1.0" encoding="UTF-8"?>
<jsfboot-configure xmlns="http://jsfboot.easyeip.com/jsfboot-configure"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://jsfboot.easyeip.com/jsfboot-configure http://www.easyeip.com/schema/jsfboot/jsfboot-configure-1.0.xsd ">

	<app-version>
		<product-name>guanlixitong</product-name>
		<product-version>1.0.0</product-version>
		<product-title>某某管理系统</product-title>
		<product-description> 某某行业全方位解决方案 </product-description>
		<company-name>某某公司</company-name>
		<company-description>
			<![CDATA[专业软件供应商 <a href="http://www.easyeip.com" target="_blank">进入公司网站</a>]]>
		</company-description>
	</app-version>
	
	<app-options>
		<site-theme>paradise</site-theme>
		<admin-theme>paradise</admin-theme>
		<account-realm>jsfboot-users</account-realm>
	</app-options>

	<!-- 把注册表改为使用数据库 -->
	<service-conf name="com.easyeip.jsfboot.core.registry.RegistryService">
		<service-param name="provider1" ref-service="com.easyeip.jsfboot.core.registry.service.MysqlRegistryService" />
	</service-conf>
	
	<!-- 配置注册表数据库JNDI -->
	<service-conf name="com.easyeip.jsfboot.core.registry.service.MysqlRegistryService">
		<service-param name="dataSource" value="java:comp/env/jdbc/MysqlJmsite" />
	</service-conf>
	
</jsfboot-configure>

=== ihaoqi/jsfboot/sources/jsfboot-demo/WebContent/WEB-INF/conf/jsfboot-production.xml
<?xml version="1.0" encoding="UTF-8"?>
<jsfboot-configure xmlns="http://jsfboot.easyeip.com/jsfboot-configure"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://jsfboot.easyeip.com/jsfboot-configure http://www.easyeip.com/schema/jsfboot/jsfboot-configure-1.0.xsd ">
	
	<app-version>
		<product-name></product-name>
		<product-version></product-version>
		<product-title></product-title>
	</app-version>
	
	<app-options>
		<site-theme>spark</site-theme>
		<admin-theme>rio</admin-theme>
		<account-realm>default</account-realm>
	</app-options>
	
	<service-conf name="">
		<service-param name=""/>
	</service-conf>

</jsfboot-configure>
