=== ihaoqi/jsfboot/sources/jsfboot-bundle/sources/jsfboot-module-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://jsfboot.easyeip.com/jsfboot-module" 
		elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://jsfboot.easyeip.com/jsfboot-module">

    <element name="jsfboot-module" type="tns:JsfbootModuleType"></element>



    <complexType name="MenuPageType">
    	<sequence>
    		<element name="menu-item" type="tns:MenuPageType"
    			minOccurs="0" maxOccurs="unbounded">
    		</element>
    		<element name="page-action" type="tns:PageActionType"
    			minOccurs="0" maxOccurs="unbounded">
    			<annotation>
    				<documentation></documentation>
    			</annotation>
    		</element>
    		<element name="public-pages" type="string" minOccurs="0" maxOccurs="1">
    			<annotation>
    				<documentation>公共页面，用逗号隔开；以/开头表示本模块根目录，不以/开头表示与本菜单同级目录；</documentation>
    			</annotation></element>
    	</sequence>
    	<attribute name="name" type="string" use="required">
    		<annotation>
    			<documentation>菜单ID，在整个菜单定义中要唯一；</documentation>
    		</annotation>
    	</attribute>
    	<attribute name="title" type="string" use="required">
    		<annotation>
    			<documentation>菜单标题</documentation>
    		</annotation>
    	</attribute>
    	<attribute name="icon" type="string" use="optional">
    		<annotation>
    			<documentation>
    				菜单图标，参考RIO中的定义的图标，不需要加“icon-”；
    			</documentation>
    		</annotation>
    	</attribute>
    	<attribute name="outcome" type="string" use="optional">
    		<annotation>
    			<documentation>要输出的页面名称，如“/index”</documentation>
    		</annotation>
    	</attribute>
    	<attribute name="explain" type="string" use="optional"></attribute>
    </complexType>





    <complexType name="JsfbootModuleType">
    	<all>
    		<element name="module-version" type="tns:ModuleVersionType"
    			minOccurs="1" maxOccurs="1">
    		</element>
    		<element name="page-resource" type="tns:PageResourceType"
    			minOccurs="0" maxOccurs="1">
    		</element>
    		<element name="account-realm" type="tns:AccountRealmType"
    			minOccurs="0" maxOccurs="1">
    		</element>

    		<element name="define-service" type="tns:DefineServiceType"
    			minOccurs="0" maxOccurs="1">
    		</element>
    		<element name="define-theme" type="tns:DefineThemeType"
    			minOccurs="0" maxOccurs="1">
    		</element>
    		<element name="data-source" type="tns:DataSourceType"
    			minOccurs="0" maxOccurs="1">
    		</element>
    	</all>
    	<attribute name="load-on-startup" type="int" use="optional" default="0"></attribute>
    </complexType>

    <complexType name="ModuleVersionType">
    	<all>
    		<element name="module-name" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="module-version" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="module-title" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="module-description" type="string"
    			minOccurs="0" maxOccurs="1">
    		</element>
    		<element name="company-name" type="string" minOccurs="0"
    			maxOccurs="1">
    		</element>
    		<element name="company-description" type="string"
    			minOccurs="0" maxOccurs="1">
    		</element>
    	</all>
    </complexType>


    <complexType name="DefineServiceType">
    	<sequence>
    		<element name="service" type="tns:ServiceItemType" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>


    <complexType name="PageResourceType">
        <annotation>
        	<documentation></documentation>
        </annotation>
        <all>
        	<element name="site-menu" type="tns:UserMenuType"
        		minOccurs="0" maxOccurs="1">
        		<annotation>
        			<documentation>定义用户使用的菜单</documentation>
        		</annotation>
        	</element>
        	<element name="admin-menu" type="tns:BackMenuType"
        		minOccurs="0" maxOccurs="1">
        		<annotation>
        			<documentation>定义后台配置的菜单</documentation>
        		</annotation>
        	</element>

        	<element name="conf-page" type="string" minOccurs="0" maxOccurs="1">
        		<annotation>
        			<documentation>模块配置页面</documentation>
        		</annotation></element>
        	<element name="public-pages" type="string" minOccurs="0"
        		maxOccurs="1">
        		<annotation>
        			<documentation>公共页面资源，不需任何权限就可访问，如index.xhtml，syspages/*。</documentation>
        		</annotation>
        	</element>
        </all>

    </complexType>





    <complexType name="ServiceItemType">
    	<sequence>
    		<element name="option" type="tns:ServiceOptionType"
    			minOccurs="0" maxOccurs="unbounded">
    			<annotation>
    				<documentation>服务可配置的参数列表；</documentation>
    			</annotation>
    		</element>
    	</sequence>
    	<attribute name="name" type="string" use="required">
    		<annotation>
    			<documentation>服务的名称，建议为服务的接口名称；</documentation>
    		</annotation>
    	</attribute>
    	<attribute name="class" type="string" use="required">
    		<annotation>
    			<documentation>服务要创建的类，必须有默认构造函数；</documentation>
    		</annotation>
    	</attribute>
        <attribute name="explain" type="string" use="optional"></attribute>
    </complexType>

    <complexType name="ServiceOptionType">
        <all>
        	<element name="explain" type="string" minOccurs="0"
        		maxOccurs="1">
        	</element>
        	<element name="value" type="string" minOccurs="0"
        		maxOccurs="1">
        		<annotation>
        			<documentation>缺省值</documentation>
        		</annotation>
        	</element>
        	<element name="ref-service" type="string" minOccurs="0" maxOccurs="1">
        		<annotation>
        			<documentation>引用服务</documentation>
        		</annotation></element>
        </all>
        <attribute name="name" type="string" use="required">
    		<annotation>
    			<documentation>参数名称；</documentation>
    		</annotation>
    	</attribute>
    </complexType>

    <complexType name="AccountRealmType">
    	<choice>
    		<element name="use-class" type="string" minOccurs="0"
    			maxOccurs="1">
    			<annotation>
    				<documentation>实现了UserAdapter接口的类名；</documentation>
    			</annotation>
    		</element>
    		<element name="ref-service"
    			type="string" minOccurs="0"
    			maxOccurs="1">
    		</element>
    	</choice>
        <attribute name="title" type="string" use="required"></attribute>
        <attribute name="explain" type="string" use="optional"></attribute>
    </complexType>


    <complexType name="DefineThemeType">
    	<all>
    		<element name="primefaces-theme" type="string" minOccurs="0"
    			maxOccurs="1">
    		</element>
    		<element name="page-template"
    			type="tns:ThemePageTemplateType" minOccurs="1" maxOccurs="1">
    		</element>
    		<element name="conf-page" type="string" minOccurs="0"
    			maxOccurs="1">
    		</element>
            <element name="login-page" type="string" minOccurs="0" maxOccurs="1"></element>
            <element name="menu-position" type="tns:MenuPositionType"
    			minOccurs="0" maxOccurs="1">
    		</element>
    		<element name="extend-template"
    			type="tns:ThemeExtendTemplateType" minOccurs="0" maxOccurs="1">
    		</element>
    	</all>
    	<attribute name="image" type="string" use="optional">
    		<annotation>
    			<documentation>
    				主题缩略图在模块下的路径，如/image/preview.png
    			</documentation>
    		</annotation>
    	</attribute>
    	<attribute name="explain" type="string" use="optional"></attribute>
    	<attribute name="use-site" type="boolean" use="required"></attribute>
    	<attribute name="use-admin" type="boolean" use="required"></attribute>
    </complexType>

    <complexType name="ThemePageTemplateType">
        <all>
        	<element name="main-page" type="string" minOccurs="1"
        		maxOccurs="1">
        		<annotation>
        			<documentation>含导航、标题的完整页面</documentation>
        		</annotation>
        	</element>
        	<element name="only-content" type="string" minOccurs="0"
        		maxOccurs="1">
        		<annotation>
        			<documentation>权内容区页面，不含导航、标题等</documentation>
        		</annotation>
        	</element>
        	<element name="blank-page" type="string" minOccurs="0" maxOccurs="1">
        		<annotation>
        			<documentation>空白页面</documentation>
        		</annotation></element>
        </all>
    </complexType>
    
    <complexType name="ThemeExtendTemplateType">
    	<sequence>
    		<element name="template"
    			type="tns:ThemeTemplateItemType" minOccurs="0" maxOccurs="unbounded">
    		</element>
    	</sequence>
    </complexType>

    <complexType name="ThemeTemplateItemType">
    	<attribute name="name" type="string" use="required"></attribute>
    	<attribute name="title" type="string" use="required"></attribute>
    	<attribute name="outcome" type="string" use="required"></attribute>
    </complexType>


    <complexType name="MenuPositionType">
    	<sequence>
    		<element name="position" type="tns:PositionItemType" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="PositionItemType">
    	<attribute name="name" type="string" use="required"></attribute>
    	<attribute name="title" type="string" use="required"></attribute>
    </complexType>

    <complexType name="BackMenuType">
    	<sequence>
    		<element name="menu-item" type="tns:MenuPageType"
    			minOccurs="0" maxOccurs="unbounded">
    		</element>
    	</sequence>
    	<attribute name="anchor" type="string" use="required"></attribute>
    	<attribute name="position" use="optional">
    		<simpleType>
    			<restriction base="string">
    				<enumeration value="child"></enumeration>
    				<enumeration value="next"></enumeration>
    			</restriction>
    		</simpleType>
    	</attribute>
    </complexType>

    <complexType name="UserMenuType">
    	<sequence>
            <element name="use-service" type="string" minOccurs="0" maxOccurs="1">
            	<annotation>
            		<documentation>使用一个服务来生成菜单项，服务必须实现了com.easyeip.jsfstarter.core.module.UserMenuProvider接口。</documentation>
            	</annotation></element>
            <element name="menu-item" type="tns:MenuPageType"
    			minOccurs="0" maxOccurs="unbounded">
    		</element>
    	</sequence>
    </complexType>


    <complexType name="DataSourceType">
    	<attribute name="required" type="boolean" use="required" fixed="true">
    		<annotation>
    			<documentation>是否需要数据源，默认为false</documentation>
    		</annotation></attribute>
    	<attribute name="explain" type="string" use="required">
    		<annotation>
    			<documentation>数据源应用介绍</documentation>
    		</annotation></attribute>
    	<attribute name="default" type="string" use="optional">
    		<annotation>
    			<documentation>默认的数据源名称</documentation>
    		</annotation></attribute>
    </complexType>

    <complexType name="PageActionType">
    	<sequence>
    		<element name="public-pages" type="string" minOccurs="0" maxOccurs="1"></element>
    	</sequence>
    	<attribute name="name" type="string" use="required"></attribute>
    	<attribute name="title" type="string" use="required"></attribute>
    	<attribute name="icon" type="string" use="optional"></attribute>
    	<attribute name="outcome" type="string" use="optional">
    		<annotation>
    			<documentation>
    				动作对应的页面；以/开头表示本模块根目录，不以/开头表示与本菜单同级目录；
    			</documentation>
    		</annotation>
    	</attribute>
    </complexType>
</schema>

=== ihaoqi/jsfboot/sources/jsfboot-admin/META-INF/jsfboot-module.xml
<?xml version="1.0" encoding="UTF-8"?>
<jsfboot-module xmlns="http://jsfboot.easyeip.com/jsfboot-module"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://jsfboot.easyeip.com/jsfboot-module http://www.easyeip.com/schema/jsfboot/jsfboot-module-1.0.xsd"
	load-on-startup="-99">
	
	<module-version>
		<module-name>jsfboot-admin</module-name>
		<module-title>jsfboot后台管理</module-title>
		<module-version>1.0.0</module-version>
		<company-name>www.easyeip.com</company-name>
		<company-description>瑞宝软件</company-description>
	</module-version>
	
	<define-service>

		<service name="com.easyeip.jsfboot.admin.datasource.CustomDataSourceService"
				class="com.easyeip.jsfboot.admin.datasource.service.CustomDataSourceServiceImpl"
				explain="admin自定义数据源">
		</service>
		
		<service name="com.easyeip.jsfboot.admin.AdminScheduleService"
				class="com.easyeip.jsfboot.admin.schedule.impl.AdminScheduleServiceImpl"
				explain="admin任务执行管理">
		</service>

	</define-service>
	
	<page-resource>
		<admin-menu anchor="">
			<menu-item name="dashboard" title="系统信息" outcome="/dashboard" icon="fa fa-laptop"/>
			<menu-item name="system" title="控制面板" icon="fa fa-cog">
				<menu-item name="console" title="模块选项" outcome="/console" icon="fa fa-cube">
					<public-pages>
						/console/module_info.xhtml,
						/console/module_conf.xhtml,
						/console/theme_conf.xhtml
					</public-pages>
				</menu-item>
				<menu-item name="data-sources" title="数据连接" outcome="/data-sources" icon="fa fa-link">
					<public-pages>
						/data-sources/add-custom.xhtml
					</public-pages>
				</menu-item>
				<menu-item name="nav-menus" title="导航菜单" outcome="/nav-menus" icon="fa fa-windows">
					<public-pages>
						/nav-menus/new-menu.xhtml,
						/nav-menus/pos-mgr.xhtml
					</public-pages>
				</menu-item>
				<menu-item name="registry" title="统一配置" outcome="/registry" icon="fa fa-slack"/>
			</menu-item>
		</admin-menu>
		<public-pages>
			font-icons.xhtml
		</public-pages>
	</page-resource>

</jsfboot-module>

=== ihaoqi/jsfboot/sources/jsfboot-demo/WebContent/META-INF/demo.jsfboot-module.xml
<?xml version="1.0" encoding="UTF-8"?>
<jsfboot-module xmlns="http://jsfboot.easyeip.com/jsfboot-module"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://jsfboot.easyeip.com/jsfboot-module http://www.easyeip.com/schema/jsfboot/jsfboot-module-1.0.xsd ">
	<module-version>
		<module-name>jsfboot-demo</module-name>
		<module-title>jsfboot-演示模块</module-title>
		<module-version>1.0.0</module-version>
	</module-version>
	
	<page-resource>
		<site-menu>
			<menu-item name="demo1" title="测试页面1" icon="fa fa-bed" outcome="/demo1">
			</menu-item>
		</site-menu>
	</page-resource>
	
</jsfboot-module>

=== ihaoqi/jsfboot/sources/jsfboot-dictionary/META-INF/jsfboot-module.xml
<?xml version="1.0" encoding="UTF-8"?>
<jsfboot-module xmlns="http://jsfboot.easyeip.com/jsfboot-module"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://jsfboot.easyeip.com/jsfboot-module http://www.easyeip.com/schema/jsfboot/jsfboot-module-1.0.xsd"
	load-on-startup="-99">
	
	<module-version>
		<module-name>jsfboot-dictionary</module-name>
		<module-title>jsfboot字典管理</module-title>
		<module-version>1.0.0</module-version>
		<company-name>www.easyeip.com</company-name>
		<company-description>瑞宝软件</company-description>
	</module-version>
	
	<define-service>
	
		<service name="com.easyeip.jsfboot.admin.dictionary.AdminDictionaryService"
				class="com.easyeip.jsfboot.admin.dictionary.impl.AdminDictionaryServiceImpl"
				explain="admin通用字典服务">
		</service>

	</define-service>
	
	<page-resource>
		<admin-menu anchor="system">
			<menu-item name="dictionary" title="数据字典" outcome="/dictionary" icon="fa fa-book"/>
		</admin-menu>
	</page-resource>

</jsfboot-module>

=== ihaoqi/jsfboot/sources/jsfboot-helpview/META-INF/jsfboot-module.xml
<?xml version="1.0" encoding="UTF-8"?>
<jsfboot-module xmlns="http://jsfboot.easyeip.com/jsfboot-module"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://jsfboot.easyeip.com/jsfboot-module http://www.easyeip.com/schema/jsfboot/jsfboot-module-1.0.xsd"
	load-on-startup="-99">
	
	<module-version>
		<module-name>jsfboot-helpview</module-name>
		<module-title>jsfboot帮助页面浏览</module-title>
		<module-version>1.0.0</module-version>
		<company-name>www.easyeip.com</company-name>
		<company-description>瑞宝软件</company-description>
	</module-version>
	
	<define-service>
	
		<service name="com.easyeip.jsfboot.admin.AdminHelpViewService"
				class="com.easyeip.jsfboot.admin.help.impl.AdminHelpViewServiceImpl"
				explain="admin帮助浏览服务">
		</service>
	
	</define-service>
	
	<page-resource>
		<public-pages>/help.xhtml</public-pages>
	</page-resource>

</jsfboot-module>

=== ihaoqi/jsfboot/sources/jsfboot-bundle/META-INF/jsfboot-module.xml
<?xml version="1.0" encoding="UTF-8"?>
<jsfboot-module xmlns="http://jsfboot.easyeip.com/jsfboot-module"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://jsfboot.easyeip.com/jsfboot-module http://www.easyeip.com/schema/jsfboot/jsfboot-module-1.0.xsd"
	load-on-startup="-100">
	
	<module-version>
		<module-name>jsfboot-bundle</module-name>
		<module-title>jsfboot驱动程序</module-title>
		<module-version>1.0.0</module-version>
		<company-name>www.easyeip.com</company-name>
		<company-description>瑞宝软件</company-description>
	</module-version>
	
	<define-service>
		<service	name="com.easyeip.jsfboot.core.registry.RegistryService"
					class="com.easyeip.jsfboot.core.registry.service.DefaultRegistryService"
					explain="jsfboot注册表服务">
			<option name="provider">
				<explain>注册表服务实现，必须支持com.easyeip.jsfboot.core.registry.RegistryService接口。</explain>
				<ref-service>com.easyeip.jsfboot.core.registry.service.XmlFileRegistryService</ref-service>
			</option>
		</service>

		<service	name="com.easyeip.jsfboot.core.secutiry.SecutiryService"
					class="com.easyeip.jsfboot.core.secutiry.admin.DefaultSecutiryService"
					explain="jsfboot访问授权服务">
		</service>
		
		<service	name="com.easyeip.jsfboot.core.surface.SurfaceService"
					class="com.easyeip.jsfboot.core.surface.impl.DefaultSurfaceService"
					explain="jsfboot主题管理服务">
		</service>

		<service	name="com.easyeip.jsfboot.core.jdbc.DataSourceService"
					class="com.easyeip.jsfboot.core.jdbc.impl.DefaultDataSourceService"
					explain="jsfboot数据源管理服务">
		</service>
		
		<service	name="com.easyeip.jsfboot.core.registry.service.XmlFileRegistryService"
					class="com.easyeip.jsfboot.core.registry.service.XmlFileRegistryService"
					explain="基于xml文件的注册表实现">
			<option name="filePath">
				<explain>xml注册表文件保存路径</explain>
				<value></value>
			</option>
			<option name="saveDelay">
				<explain>最后一次修改后多久才保存（毫秒）</explain>
				<value>3000</value>
			</option>
		</service>
	</define-service>
	
	<page-resource>
		<public-pages>/admin-access-denied.xhtml,/site-access-denied.xhtml</public-pages>
	</page-resource>
	
</jsfboot-module>

=== ihaoqi/jsfboot/sources/jsfboot-theme/META-INF/paradise.jsfboot-module.xml
<?xml version="1.0" encoding="UTF-8"?>
<jsfboot-module xmlns="http://jsfboot.easyeip.com/jsfboot-module"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://jsfboot.easyeip.com/jsfboot-module http://www.easyeip.com/schema/jsfboot/jsfboot-module-1.0.xsd">
	
	<module-version>
		<module-name>paradise</module-name>
		<module-title>jsfboot经典主题</module-title>
		<module-version>1.0.0</module-version>
		<company-name>www.easyeip.com</company-name>
		<company-description>瑞宝软件</company-description>
	</module-version>
	
	<page-resource>
		<public-pages>
			/error/viewExpired.xhtml,
			/error/IllegalArgument.xhtml
		</public-pages>
	</page-resource>
	
	<define-theme image="/images/paradise.png" use-admin="true" use-site="true">
		<page-template>
			<main-page>/template/template.xhtml</main-page>
			<blank-page>/template/template-blank.xhtml</blank-page>
			<only-content>/template/template-content.xhtml</only-content>
		</page-template>
		<menu-position>
			<position name="user" title="用户菜单"/>
			<position name="link" title="页脚链接"/>
		</menu-position>
		<conf-page>/config.xhtml</conf-page>
		<login-page>/login.xhtml</login-page>
		<primefaces-theme>paradise-#{paradiseTheme.config.widgetColor}</primefaces-theme>
	</define-theme>

</jsfboot-module>

=== ihaoqi/jsfboot/sources/jsfboot-webfile/META-INF/jsfboot-module.xml
<?xml version="1.0" encoding="UTF-8"?>
<jsfboot-module xmlns="http://jsfboot.easyeip.com/jsfboot-module"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://jsfboot.easyeip.com/jsfboot-module http://www.easyeip.com/schema/jsfboot/jsfboot-module-1.0.xsd">
	
	<module-version>
		<module-name>jsfboot-webfile</module-name>
		<module-title>jsfboot文件管理</module-title>
		<module-version>1.0.0</module-version>
		<company-name>www.easyeip.com</company-name>
		<company-description>瑞宝软件</company-description>
	</module-version>
	
	<define-service>
		<service name="com.easyeip.jsfboot.webfile.WebfileResourceService"
				class="com.easyeip.jsfboot.webfile.service.WebfileResourceServiceImpl"
				explain="Web文件管理服务">
			<option name="provider">
				<explain>web文件管理实现，支持registry、winlinux两种，默认为registry。</explain>
				<value>registry</value>
			</option>
		</service>
		<service name="com.easyeip.jsfboot.webfile.WebfileDownloadService"
				class="com.easyeip.jsfboot.webfile.service.WebfileDownloadServiceImpl"
				explain="web文件下载服务">
		</service>
	</define-service>

	<page-resource>
		<admin-menu anchor="system">
			<menu-item name="multimedia" title="文件资源" outcome="/multimedia" icon="fa fa-image">
				<public-pages>/custom-path.xhtml</public-pages>
			</menu-item>
		</admin-menu>
		<!-- 
		<admin-menu anchor="">
			<menu-item name="resource" title="文件管理" icon="fa fa-hdd-o">
				<menu-item name="multimedia" title="文件资源" outcome="/multimedia" icon="fa fa-image">
					<public-pages>/custom-path.xhtml</public-pages>
				</menu-item>
				<menu-item name="download" title="下载管理" outcome="/download" icon="fa fa-cloud-download"/>
				<menu-item name="web-pages" title="页面设计" outcome="/download" icon="fa fa-delicious"/>
				<menu-item name="web-articles" title="文章管理" outcome="/download" icon="fa fa-file-word-o"/>
			</menu-item>
		</admin-menu>
		 -->
	</page-resource>

</jsfboot-module>

=== ihaoqi/jsfboot/sources/jsfboot-spring-security/META-INF/jsfboot-module.xml
<?xml version="1.0" encoding="UTF-8"?>
<jsfboot-module xmlns="http://jsfboot.easyeip.com/jsfboot-module"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://jsfboot.easyeip.com/jsfboot-module http://www.easyeip.com/schema/jsfboot/jsfboot-module-1.0.xsd">
	
	<module-version>
		<module-name>jsfboot-spring-security</module-name>
		<module-title>jsfboot安全spring-security实现</module-title>
		<module-version>1.0.0</module-version>
		<company-name>www.easyeip.com</company-name>
		<company-description>瑞宝软件</company-description>
	</module-version>
	

	<define-service>
		<service name="com.easyeip.jsfboot.secutiry.spring.SecurityContextRegisterService"
				class="com.easyeip.jsfboot.secutiry.spring.SecurityContextRegisterService"
				explain="向jsfboot注册spring-security上下文">
		</service>
	</define-service>

</jsfboot-module>
